### ISSUE TITLE
[OPTIMADE] Support for queries on `structure_features`

### ISSUE THREAD

**Issue by CasperWA** [httk/httk#32]
When testing queries to `/structures`, the OPTIMADE server fails (`500 Internal Server Error`) when filtering on the mandatory query field `structure_features`: http://optimade.openmaterialsdb.se/v1.0.0/structures?filter=NOT%20structure_features%20HAS%20ALL%20%22assemblies%22

**Comment by rartino** [comment]
Thanks for reporting this! The filter operators on these very special fields are tricky to get right :-). It should be fixed now. Please report any other issues you find.
